### ISSUE TITLE
Different URL for CMS and Frontend

### ISSUE THREAD

**Issue by perret123** [collective/collective.siteimprove#11]
Hello all

We use a customized Plone 5.2 with a different URL for the CMS and the Frontend. 

When we use the SiteImprove plugin, it always tries to search the pages using the WebCMS Url (like webcms.domain.com instead of www.domain.com) - so sadly we can't use it.

Is there any way we can change this behavior? Any tips are appreciated - if this needs a sourcecode change and you don't have the time for it, it would also be nice to know a starting point where we should try to handle this behavior.

Thank you very much.

Best regards
Michael

**Comment by skleinfeldt** [comment]
@perret123 sorry for the slow response. We're going to work on this feature the week of July 6. The consensus is that it would be easier to do it than to explain how to do it!

**Comment by perret123** [comment]
@skleinfeldt Thank you! Very much appreciated 👍

**Comment by alecpm** [comment]
This feature is included in the 1.0.6 release.
