### ISSUE TITLE
Fix Python 3 compatibility

### ISSUE THREAD

**Issue by fiterbek** [collective/collective.siteimprove#12]
Hi, 

We're using this addon in our dev Plone 5.2 site, but it seems we need to use https://github.com/collective/collective.siteimprove/tree/plone5 to get it working on python 3. 

When using collective.siteimprove 1.0.5 we get a ModuleNotFoundError: No module named 'email.Utils' , triggered on /collective/siteimprove/browser/events.py", line 2, in <module>
    from email.Utils import formatdate

Could you merge the plone5 branch and create a new release?

**Comment by alecpm** [comment]
Python 3 compatibility has been added in release 1.0.6.

**Comment by fiterbek** [comment]
Thank you for the lightning merge & release!
