### ISSUE TITLE
Save-button on the controlpanel doesn't work

### ISSUE THREAD

**Issue by batlock666** [collective/collective.siteimprove#7]
The save-button on the controlpanel doesn't work. When I enter a value for the token and click save, the controlpanel page reloads, and the value is still visible, but there is no "Changes saved." message. When I reload again, the value in the field has disappeared. However, if I remove the "Request new token"-button in the code (by commenting out the button handler), the save button works as it should.

**Comment by tkimnguyen** [comment]
Which versions of c.siteimprove and Plone are you seeing this with? Is this when using the default theme?

**Comment by batlock666** [comment]
collective.siteimprove = 1.0.3
Products.CMFPlone = 5.1.4

This is on a freshly installed Plone site, with the default Plone 5 theme. collective.siteimprove:default is the only installed profile. It has something to do with the way the save- and cancel-buttons are copied from RegistryEditForm. If I replace this line in controlpanel.py:

    buttons = controlpanel.RegistryEditForm.buttons.copy()

with these button handlers:

    @button.buttonAndHandler(_(u"Save"), name="save")
    def handleSave(self, action):
        super(SiteimproveControlPanelForm, self).handleSave(self, action)

    @button.buttonAndHandler(_(u"Cancel"), name="cancel")
    def handleCancel(self, action):
        super(SiteimproveControlPanelForm, self).handleCancel(self, action)

then everything works as it should.

**Comment by witekdev** [comment]
Thank you

**Comment by skleinfeldt** [comment]
@batlock666 thank you very much for the contribution. We've made a 1.0.4 release which includes the fix. Again, sorry for not noticing until now.
